---
title: "Amit's Social Analytics"
author: "Rajneesh Sharma"
date: "10/25/2023"
output: html_document
---

```{r}
library(readxl)
library(leaps)
library(tidyverse)

data <- read_excel("E:/GIS/Amit's Social Analytics/Cleaned_dataset.xlsx")


regfit.full=regsubsets(`No. of pashmina goats`~.,data) #select the best model in terms of RSS
summary(regfit.full)

anova <- aov(`No. of pashmina goats`~.,data)
summary(anova) 

#TukeyHSD(anova)
```

```{r}
reg.summary=summary(regfit.full)
reg.summary

reg.summary$rsq

```

```{r}
par(mfrow=c(2,2))
plot(reg.summary$rss,xlab="Number of Variables",ylab="RSS",type="l")
plot(reg.summary$adjr2,xlab="Number of Variables",ylab="Adjusted RSq",type="l")
which.max(reg.summary$adjr2)

points(2,reg.summary$adjr2[2], col="red",cex=2,pch=20)
plot(reg.summary$cp,xlab="Number of Variables",ylab="Cp",type='l')
which.min(reg.summary$cp)

points(1,reg.summary$cp[1],col="red",cex=2,pch=20)
which.min(reg.summary$bic)

plot(reg.summary$bic,xlab="Number of Variables",ylab="BIC",type='l')
points(1,reg.summary$bic[1],col="red",cex=2,pch=20)


plot(regfit.full,scale="r2")


plot(regfit.full,scale="adjr2")


plot(regfit.full,scale="Cp")

plot(regfit.full,scale="bic")

lm_model= lm(`No. of pashmina goats` ~ `Wealth rank` + `No. of eductaed members`, data)
summary(lm_model)

Anova=aov(data$`No. of pashmina goats` ~ data$`No. of eductaed members`+ data$`Wealth rank`)

plot(Anova)

#posthoc <- TukeyHSD(x=Anova, conf.level=0.95)



```

Multi T-test function

```{r}
# matrix of t-test
# mat : data.frame or matrix
# ... : further arguments to pass to the t.test function
multi.ttest <- function(mat, ...) {
  mat <- as.matrix(mat)
  n <- ncol(mat)
  p.mat<- matrix(NA, n, n)
  diag(p.mat) <- 1
  for (i in 1:(n - 1)) {
    for (j in (i + 1):n) {
      test <- t.test(mat[, i], mat[, j], ...)
      p.mat[i, j] <- p.mat[j, i] <- test$p.value
    }
  }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  signif(p.mat,4)
}

```

```{r}
p.mat<-multi.ttest(data[,1:9])
p.mat


# Hide upper triangle
upper<-p.mat
upper[upper.tri(p.mat)]<-""
upper<-as.data.frame(upper)
upper
```

```{r}
data_plot=data%>%
  select("No. of pashmina goats","Total livestock","Total family members","Full time pastorals","No. of eductaed members", "No. of males","No. of females","Wealth rank","Per capita livestock", "Kiang count estimates_2")

data_plot$`Proportion of Educated Members`=data_plot$`No. of eductaed members`/data$`Total family members`

data_plot
data_plot <- subset(data_plot, select = -c(`No. of eductaed members`))


str(data_plot)
data_scaled=as.data.frame(scale(data_plot, center = TRUE, scale = TRUE))

data_scaled=na.omit(data_scaled)
```

```{r}

corrplot2 <- function(data,
                      method = "spearman",
                      sig.level = 0.1,
                      order = "original",
                      diag = FALSE,
                      type = "upper",
                      tl.srt = 45,
                      number.font = 1,
                      number.cex = 1,
                      mar = c(0, 0, 0, 0)) {
  library(corrplot)
  data_incomplete <- data
  data <- data[complete.cases(data), ]
  mat <- cor(data, method = method)
  cor.mtest <- function(mat, method) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat <- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
      for (j in (i + 1):n) {
        tmp <- cor.test(mat[, i], mat[, j], method = method)
        p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
      }
    }
    colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
    p.mat
  }
  p.mat <- cor.mtest(data, method = method)
  col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
  corrplot(mat,
    method = "color", col = col(200), number.font = number.font,
    mar = mar, number.cex = number.cex,
    type = type, order = order,
    addCoef.col = "black", # add correlation coefficient
    tl.col = "black", tl.srt = tl.srt, # rotation of text labels
    # combine with significance level
    p.mat = p.mat, sig.level = sig.level, insig = "label_sig",
    pch = 0.5,
  pch.col = "black",
  pch.cex = 2,
    # hide correlation coefficiens on the diagonal
    diag = diag
  )
}



corrplot2(
  data = data_scaled,
  method = "spearman",
  sig.level = 0.1,
  order = "original",
  diag = FALSE,
  type = "upper",
  tl.srt = 45
)


```


```{r}
library(Hmisc)

# Mark the insignificant coefficients according to the specified p-value significance level
cor_5 <- rcorr(as.matrix(data_scaled), type=c("spearman"))
M <- cor_5$r
p_mat <- cor_5$P

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(M, method = "color", col = col(200),  
         type = "upper", order = "original", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col = "darkblue", tl.srt = 45, #Text label color and rotation
         # Combine with significance level
         p.mat = p_mat, sig.level = 0.1,  
         # hide correlation coefficient on the principal diagonal
         diag = FALSE)

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(M, method="color", col=col(200),  
         type="upper", order="original", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p_mat, sig.level = 0.1, insig = "n", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )
```

```{r}
library(Hmisc)
library(corrplot) # Ensure corrplot is loaded

png("E:/GIS/Amit's Social Analytics/Figures/cor_plot.png", width = 8, height = 6, units = 'in', res = 330)
# Assuming data_scaled and necessary libraries are loaded
cor_5 <- rcorr(as.matrix(data_scaled), type=c("spearman"))
M <- cor_5$r
p_mat <- cor_5$P

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))

# Open a graphical device to plot off-screen
# This step is necessary if you're running this in a non-interactive environment
# Otherwise, you can omit this line if running in an interactive R session
# png(file = NULL) # Uncomment if needed

corrplot(M, method = "color", col = col(200),  
         type = "upper", order = "original", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col = "darkblue", tl.srt = 45, #Text label color and rotation
         # Combine with significance level
        p.mat = p_mat, sig.level = 0.1, insig = "pch", 
         # hide correlation coefficient on the principal diagonal
         diag = FALSE)

# Save the plot to an object
p1 <- recordPlot()
p1
ggsave("E:/GIS/Amit's Social Analytics/Figures/cor_plot.png" , width = 6, height = 6, units = c("in"), dpi = 330)
dev.off()

```


